#!/bin/bash
#
# nxdesktop_helper - Small helper for external rdesktop program as needed by NX 3.0.0 backend.
#
# Copyright (c) 2007 by Fabian Franz <freenx@fabian-franz.de>
#
# License: GPL, v2
#
# SVN: $Id $
#

[ -z "$COMMAND_RDESKTOP" ] && COMMAND_RDESKTOP="rdesktop"

# Workaround for NXClient 3.2.0, sending wrong keyboard layout
[ "$agent_keyboard" = "ch" ] && agent_keyboard="de-ch"

# setup commandline
set -- -f -u "$agent_user" -k "$agent_keyboard" -d "$agent_domain" $AGENT_EXTRA_OPTIONS_RDP "$agent_server"

if [ -n "$agent_password" ]
then
	echo $agent_password | $COMMAND_RDESKTOP -p - "$@"
else
	$COMMAND_RDESKTOP "$@"
fi
