<div class="box">
	<h2>
		NX Clients
	</h2>
	<dl>
		<dt>
			NoMachine Client (Windows, Linux, MacOS/X, Solaris)
		</dt>
		<dd>
			<a href="http://www.nomachine.com/download.php">http://www.nomachine.com/download.php</a>
			<p><img src="nmc1.jpg" width="342" height="214" border="0" alt="screenshot: client connecting to a server"></p>
			<p><img src="nmc2.jpg" width="384" height="547" border="0" alt="screenshot: client configuration dialog"></p>
		</dd>
	</dl>
</div>
