<div class="box">
	<h2>
		Official FreeNX Server Packages
	</h2>
	<p>
		This tarball is intented mainly for distributions, which want to use FreeNX as building the other OpenSource NX components is quite difficult.
	</p>
	<p>
		<a href="http://download.berlios.de/freenx/">freenx-X.Y.Z.tar.gz</a>
	</p>
	<p>
		You probably want to download the <a href="http://www.nomachine.com/sources/">NX sources</a> together with this package. Read the building instructions at <a href="http://www.nomachine.com/documentation/building-components.php">http://www.nomachine.com/documentation/building-components.php</a>.
	</p>
</div>
<div class="box">
	<h2>
		Packages for your Distribution
	</h2>
	<dl>
		<dt>
			Debian/Ubuntu DEBs
		</dt>
<!--		<dd>
			<a href="http://kanotix.com/files/debian/pool/main/f/freenx/">http://kanotix.com/files/debian/pool/main/f/freenx/</a>
		</dd>
                <dd>
                        <a href="http://kalyxo-archive.mornfall.net/pool/main/f/freenx/">http://kalyxo-archive.mornfall.net/pool/main/f/freenx/</a>
                </dd>
		<dd>
			<a href="http://www.linux.lk/~anuradha/nx/">http://www.linux.lk/~anuradha/nx/</a>
		</dd> -->
		<dd>
			<a href="http://packages.debianbase.de/">http://packages.debianbase.de/</a>
		</dd>
		<dt>
			CentOS RPMs &amp; HOWTO
		</dt>
		<dd>
			<a href="http://wiki.centos.org/FreeNX">http://wiki.centos.org/FreeNX</a>
		</dd>
		<dt>
			Fedora/Redhat RPMs &amp; HOWTO
		</dt>
		<dd>
			<a href="http://fedoranews.org/contributors/rick_stout/freenx/">http://fedoranews.org/contributors/rick_stout/freenx/</a>
		</dd>
		<dt>
			FreeBSD ports
		</dt>
		<dd>
			<a href="http://www.deweyonline.com/nx/freebsd.html">http://www.deweyonline.com/nx/freebsd.html</a>
		</dd>
		<dt>
			Gentoo
		</dt>
		<dd>
			See our <a href="info.php">information section</a> or just use emerge.
		</dd>
		<dt>
			Suse RPMs
		</dt>
		<dd>
			<a href="ftp://ftp.suse.com/pub/suse/i386/supplementary/X/NX/">ftp://ftp.suse.com/pub/suse/i386/supplementary/X/NX/</a>
		</dd>
	</dl>
</div>
