<div class="box">
	<h2>
		NX Technology
	</h2>
	<dl>
		<dt>
			Introduction
		</dt>
		<dd>
			<a href="http://nomachine.com/documentation/html/intr-technology.html">http://nomachine.com/documentation/html/intr-technology.html</a>
		</dd>
		<dt>
			NX Components &amp; Flowcharts
		</dt>
		<dd>
			<a href="http://openfacts.berlios.de/index-en.phtml?title=NX_Components">http://openfacts.berlios.de/index-en.phtml?title=NX_Components</a>
		</dd>
	</dl>
</div>
<div class="box">
	<h2>
		HOWTOs &amp; FAQs
	</h2>
	<dl>
		<dt>
			General FreeNX FAQ
		</dt>
		<dd>
			<a href="http://openfacts.berlios.de/index-en.phtml?title=FreeNX_FAQ">http://openfacts.berlios.de/index-en.phtml?title=FreeNX_FAQ</a>
		</dd>
		<dd>
			<a href="http://www.gnomeuser.org/documents/howto/nx.html">http://www.gnomeuser.org/documents/howto/nx.html</a>
		</dd>
		<dt>
			Debian/Ubuntu build-from-source HOWTO
		</dt>
		<dd>
			<a href="http://stateless.geek.nz/2005/06/27/building-freenx-04-on-ubuntu-hoary/">http://stateless.geek.nz/2005/06/27/building-freenx-04-on-ubuntu-hoary/</a>
		</dd>
		<dt>
			Fedora/Redhat installation HOWTO
		</dt>
		<dd>
			<a href="http://fedoranews.org/contributors/rick_stout/freenx/">http://fedoranews.org/contributors/rick_stout/freenx/</a>
		</dd>
		<dt>
			Gentoo installation HOWTO
		</dt>
		<dd>
			<a href="http://de.gentoo-wiki.com/FreeNX_Server">http://de.gentoo-wiki.com/FreeNX_Server</a>
		</dd>
	</dl>
</div>
