#!/usr/bin/python2.4
#
# Copyright 2007 Google Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: alriddoch@google.com (Alistair Riddoch)

"""nxnode program for handling nx nodes.

"""

import sys
import signal

sys.path.append('/usr/freenx/lib')
import nxlog
import nxparser


def signal_handler(signum, unused_frame):
  nxlog.log(nxlog.LOG_DEBUG, 'Going down on signal %d' % signum)
  sys.exit(1)


def main():
  nxlog.setup('nxnode')
  nxlog.set_log_level(nxlog.LOG_DEBUG)
  nxlog.log(nxlog.LOG_DEBUG, 'Startup')
  nxlog.log(nxlog.LOG_DEBUG, 'Args %r' % sys.argv)

  signal.signal(signal.SIGINT, signal_handler)
  signal.signal(signal.SIGTERM, signal_handler)
  signal.signal(signal.SIGHUP, signal.SIG_IGN)

  parser = nxparser.node.parser(sys.stdin, sys.stdout)
  parser.banner()
  parser.loop()
  nxlog.log(nxlog.LOG_DEBUG, 'Finished')


if __name__ == '__main__':
  main()
