#!/bin/bash
#
# nxserver-login-hook - Script to login the user and check if user is allowed to login.
#
# Copyright (c) 2007 by Fabian Franz <FreeNX@fabian-franz.de>
#
# License: GPL, version 2
#
# Syntax: nxserver-login-hook auth-method user executable parameters
#

# FIXME: Read general config

SSH_PORT="22"
SSH_HOST="$HOSTNAME"
COMMAND_SU="su"
COMMAND_SSH="ssh"

#if [ "$2" = "ff" ]
#then
#	exit 1
#fi

case "$1" in
	ssh)
		exec $COMMAND_SSH -2 -x -l "$2" "$SSH_HOST" -p "$SSH_PORT" -o "NumberOfPasswordPrompts 1" "PATH=$PATH" "$3" "$4"
	;;
	su)
		exec $COMMAND_SU - "$2" -c "PATH=$PATH $3 $4"
	;;
esac

exit 1
