#!/bin/bash

# Copyright 2007 Google Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# nxfoo - Provides functionality for the freenx redesign
#
# Author: alriddoch@google.com (Alistair Riddoch)
#
# Used configuration keys:
#
# Used internal subfunctions:
#
# Used internal variables:
#
# Used internal components:
#
# Used external programs:
#
# Accepted protocol requests from client:
#
# Used protocol responses to client:
#
# FAQ-Questions:
#
# SVN: $Id: $
#

export LOG_LEVEL=7

nxlog 7 Unimplemented command $0 invoked with arguments $@
