#!/bin/bash
#
# Simple wrapper for nxssh for freenx-usermode.
#
# Copyright (c) 2005 by Fabian Franz.
#
# License: GPL
#

CONN=$(echo "$@" | sed 's/.*nx@//g' | cut -d" " -f1)

unset NXWRAP
case "$CONN" in *@*) NXWRAP=1 ;; esac

if [ "$NXWRAP" = "1" ]
then

	cat <<EOF
NX> 203 NXSSH running with pid: $$
NX> 200 Connected to address: 127.0.0.1 on port: 22
NX> 202 Authenticating user: nx
NX> 208 Using auth method: publickey
EOF

	# Login stage
	while true
	do
		echo -n "NX> 105 "
		read CMD
		# FIXME?
		[ "$CMD" = "" ] && CMD="quit"
		echo "$CMD"
		
		case "$CMD" in 
			quit|QUIT)
				echo "Quit"
				echo "NX> 999 Bye"
				exit 0
			;;
			exit|EXIT)
				echo "Exit"
				echo "NX> 999 Bye"
				exit 0
			;;
			bye|BYE)
				echo "Bye"
				echo "NX> 999 Bye"
				exit 0
			;;
			hello*|HELLO*)
				PROTO=$(echo $CMD | sed 's/.*Version \(.*\)/\1/g')
				echo "NX> 134 Accepted protocol: $PROTO"
			;;
			"set auth_mode*"|"SET AUTH_MODE*")
				if [ "$CMD" = "set auth_mode password" -o "$CMD" = "SET AUTH_MODE PASSWORD" ]
				then
					echo "Set auth_mode: password"
				else
					echo "NX> 500 ERROR: unknown auth mode ''"
				fi
			;;
			login|LOGIN)
				LOGIN_SUCCESS="0"
				
				echo_x -n "NX> 101 User: "
				read USER2
				echo_x $USER2
				
				echo_x -n "NX> 102 Password: "
				break
			;;
		esac
	done

	export SSH_ASKPASS=/usr/bin/ssh-askpass

	exec $(dirname $0)/nxssh.orig -nxstdinpass $CONN -x -2 -B sh -c "~/NX4U/bin/nxserver-usermode"
else
	exec $(dirname $0)/nxssh.orig "$@"
fi
